baseURL = "https://www.saikan.me"
title = "Sai Kandregula"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = false
PygmentsCodeFencesGuessSyntax = false
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = ""
email = ""
favicon = "/favicon.ico"
firstName = "Sai"
lastName = "Kandregula"
description = "Hey, I am researching for a master's degree in Computer Science under Prof. Srikanta Bedathur and Prof. Sayan Ranu at IIT Delhi"
phone = ""
profileImage = "img/schat.webp"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = true
showBlog = true

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://refind.com/saikan"
name = "Refind"

[[params.handles]]
link = "https://zeneca.io/sai"
name = "Zeneca"

[[params.handles]]
link = "https://github.com/decoherencer/"
name = "GitHub"

[[params.handles]]
link = "https://www.linkedin.com/in/saikan/"
name = "LinkedIn"

[[params.handles]]
link = "https://twitter.com/entangledenergy"
name = "Twitter"

# name = "binarysearch"
# https://binarysearch.com/@/skan
# name = "Duolingo"
# https://www.duolingo.com/profile/sai.kan
# https://keybase.io/saikan
# https://scholar.google.co.in/citations?hl=en&user=2kfO04oAAAAJs
# https://www.kaggle.com/saikan
# https://medium.com/@saikan
# https://www.vocabulary.com/profiles/B06AWFPA77ORA2

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = ["tags", "resume", "profile", "portfolio", "responsive" ]
